cc_library(
    name='template_compare',
    srcs=[
        './template.h'
    ],
)

cc_binary(
    name='template_test',
    srcs=[
        './unittest/template_test.cpp'
    ],
    deps=[":template_compare"]
)